FROM python:2.7.12

# PostgreSQL client
ENV PG_MAJOR 9.5
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list
RUN apt-get update \
    && apt-get install -y postgresql-client-$PG_MAJOR \
    && rm -rf /var/lib/apt/lists/*
# Specifying password so that client doesn't ask scripts for it...
ENV PGPASSWORD "metabrainz"

# Node and Less compiler
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g less less-plugin-clean-css

RUN mkdir /code
WORKDIR /code

# Python dependencies
RUN apt-get update && \
    apt-get install -y \
                    build-essential \
                    libtiff5-dev \
                    libffi-dev \
                    libxml2-dev \
                    libxslt1-dev \
                    libssl-dev && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/
RUN fab compile_styling

CMD python manage.py runserver -h 0.0.0.0 -p 80 -d
