"""Migrate users from the MusicBrainz ``editor`` table into the MetaBrainz ``user`` table.

The two tables live in different databases, so this is done over the network with a
plain Python script: MusicBrainz editors are streamed from the MusicBrainz database
(``SQLALCHEMY_MUSICBRAINZ_URI``) and inserted into the MetaBrainz database
(``SQLALCHEMY_DATABASE_URI``).

The script is idempotent, resumable and incremental. It can be re-run after an
interruption or repeatedly to keep the tables in sync: editors are upserted, and an
existing user is only updated when the MusicBrainz ``editor.last_updated`` is newer than
the stored ``user.last_updated``. Updates only touch MusicBrainz-owned columns and preserve
MetaBrainz-owned state (``login_id`` and ``is_blocked``).
"""
from uuid import uuid4

import psycopg2
from flask import current_app
from psycopg2.extras import RealDictCursor, execute_values

from metabrainz import db

# Number of editors to read from MusicBrainz and write to MetaBrainz per batch.
DEFAULT_BATCH_SIZE = 1000

FETCH_EDITORS_QUERY = """
    SELECT id,
           name,
           email,
           email_confirm_date,
           member_since,
           last_login_date,
           last_updated,
           password,
           deleted
      FROM editor
     WHERE id > %(after_id)s
  ORDER BY id
     LIMIT %(batch_size)s
"""

# Fetch the last_updated of users already imported, so we can decide which editors in a
# batch are new, changed or unchanged and avoid rewriting unchanged rows.
FETCH_EXISTING_QUERY = 'SELECT id, last_updated FROM "user" WHERE id = ANY(%(ids)s)'

# Upsert a single editor. login_id and is_blocked are deliberately left out of the
# DO UPDATE clause: login_id is generated by MetaBrainz on first import (re-generating it
# would invalidate active sessions) and is_blocked is MetaBrainz-owned moderation state.
# The DO UPDATE WHERE clause is a race guard: even if a row is sent, an older MusicBrainz
# change can never overwrite a newer one.
UPSERT_USER_QUERY = """
    INSERT INTO "user" (id, login_id, name, password, email, unconfirmed_email,
                        email_confirmed_at, member_since, last_login_at, last_updated, deleted)
         VALUES %s
    ON CONFLICT (id) DO UPDATE
       SET name = EXCLUDED.name,
           password = EXCLUDED.password,
           email = EXCLUDED.email,
           unconfirmed_email = EXCLUDED.unconfirmed_email,
           email_confirmed_at = EXCLUDED.email_confirmed_at,
           member_since = EXCLUDED.member_since,
           last_login_at = EXCLUDED.last_login_at,
           last_updated = EXCLUDED.last_updated,
           deleted = EXCLUDED.deleted
     WHERE EXCLUDED.last_updated > "user".last_updated
"""

UPSERT_USER_TEMPLATE = (
    "(%(id)s, %(login_id)s, %(name)s, %(password)s, %(email)s, %(unconfirmed_email)s, "
    "%(email_confirmed_at)s, %(member_since)s, %(last_login_at)s, %(last_updated)s, %(deleted)s)"
)


def _build_user_row(editor):
    """Map a MusicBrainz editor row to the parameters for an upsert into ``user``.

    ``login_id`` is only consumed on the INSERT path; the upsert never updates it, so an
    existing user keeps its original login_id (and therefore its active sessions).
    """
    deleted = editor["deleted"]

    if deleted:
        # Deleted editors are already anonymised in MusicBrainz; do not carry over any
        # password or email and keep the password column non-null as the schema requires.
        password = ""
        email = None
        unconfirmed_email = None
        email_confirmed_at = None
    else:
        # MusicBrainz already stores a bcrypt hash, in RFC 2307 format
        # ("{CRYPT}$2a$<cost>$<salt+hash>"). flask-bcrypt's check_password_hash feeds the
        # stored value straight to the bcrypt library, which does not understand the
        # "{CRYPT}" scheme prefix, so strip it and keep the bare bcrypt MCF string. Never
        # re-hash: that would bcrypt an already-bcrypt'd value and break every login.
        password = editor["password"] or ""
        if password.startswith("{CRYPT}"):
            password = password[len("{CRYPT}"):]

        if editor["email"] and editor["email_confirm_date"]:
            email = editor["email"]
            unconfirmed_email = None
            email_confirmed_at = editor["email_confirm_date"]
        else:
            email = None
            unconfirmed_email = editor["email"]
            email_confirmed_at = None

    return {
        "id": editor["id"],
        "login_id": str(uuid4()),
        "name": editor["name"],
        "password": password,
        "email": email,
        "unconfirmed_email": unconfirmed_email,
        "email_confirmed_at": email_confirmed_at,
        "member_since": editor["member_since"],
        "last_login_at": editor["last_login_date"],
        "last_updated": editor["last_updated"],
        "deleted": deleted,
    }


def _upsert_batch(meb_cursor, rows):
    """Upsert a batch of user rows in a single statement and return the number written.

    page_size is forced to the row count so execute_values emits one statement, which
    makes rowcount accurate (number of rows actually inserted or updated).
    """
    if not rows:
        return 0
    execute_values(meb_cursor, UPSERT_USER_QUERY, rows,
                   template=UPSERT_USER_TEMPLATE, page_size=len(rows))
    return meb_cursor.rowcount


def _needs_write(editor, existing_last_updated):
    """Decide whether an editor must be (re-)written, to avoid unnecessary writes.

    New editors always need a write. An existing user is only rewritten when MusicBrainz
    has a strictly newer ``last_updated`` than what we previously imported.
    """
    if existing_last_updated is None:
        return True
    editor_last_updated = editor["last_updated"]
    if editor_last_updated is None:
        return False
    return editor_last_updated > existing_last_updated


def _reset_user_id_sequence(meb_cursor):
    """Advance the ``user.id`` identity sequence past the imported ids.

    The ids are inserted explicitly, which does not advance the identity sequence, so new
    sign-ups would otherwise collide with imported ids.
    """
    meb_cursor.execute("""
        SELECT setval(
            pg_get_serial_sequence('"user"', 'id'),
            GREATEST((SELECT COALESCE(MAX(id), 1) FROM "user"), 1)
        )
    """)


def migrate_mb_users(batch_size=DEFAULT_BATCH_SIZE):
    """Stream MusicBrainz editors and import them into the MetaBrainz user table."""
    mb_uri = current_app.config["SQLALCHEMY_MUSICBRAINZ_URI"]
    if not mb_uri:
        raise RuntimeError("SQLALCHEMY_MUSICBRAINZ_URI is not configured.")

    meb_connection = db.engine.raw_connection()
    mb_connection = psycopg2.connect(mb_uri)
    try:
        after_id = 0
        total_written = 0
        total_skipped = 0

        with meb_connection.cursor() as meb_cursor, \
                mb_connection.cursor(cursor_factory=RealDictCursor) as mb_cursor:
            while True:
                mb_cursor.execute(FETCH_EDITORS_QUERY, {"after_id": after_id, "batch_size": batch_size})
                editors = mb_cursor.fetchall()
                if not editors:
                    break

                # Look up the users we already imported in this batch so we can skip
                # unchanged editors instead of rewriting rows that have not changed.
                meb_cursor.execute(FETCH_EXISTING_QUERY, {"ids": [e["id"] for e in editors]})
                existing = {r[0]: r[1] for r in meb_cursor.fetchall()}

                rows = [_build_user_row(editor) for editor in editors
                        if _needs_write(editor, existing.get(editor["id"]))]
                written = _upsert_batch(meb_cursor, rows)
                # Skipped = unchanged editors filtered out + rows the WHERE guard rejected.
                total_written += written
                total_skipped += len(editors) - written

                # editors are ordered by id, so the last one is the highest id in the batch.
                after_id = editors[-1]["id"]
                meb_connection.commit()
                current_app.logger.info(
                    "Migrated editors up to id %s (written=%s, skipped=%s).",
                    after_id, total_written, total_skipped,
                )

            _reset_user_id_sequence(meb_cursor)
            meb_connection.commit()

        current_app.logger.info(
            "Finished migrating MusicBrainz editors: %s written, %s skipped.",
            total_written, total_skipped,
        )
        return total_written, total_skipped
    except Exception:
        meb_connection.rollback()
        current_app.logger.error("Error while migrating MusicBrainz editors.", exc_info=True)
        raise
    finally:
        mb_connection.close()
        meb_connection.close()
