BEGIN;

CREATE TABLE "user" (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name                    TEXT NOT NULL,
    password                TEXT NOT NULL,
    email                   TEXT UNIQUE,
    unconfirmed_email       TEXT,
    email_confirmed_at      TIMESTAMP WITH TIME ZONE,
    member_since            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_login_at           TIMESTAMP WITH TIME ZONE,
    last_updated            TIMESTAMP WITH TIME ZONE,
    deleted                 BOOLEAN
);

ALTER TABLE "user" ADD CONSTRAINT user_pkey PRIMARY KEY (id);

COMMIT;
