BEGIN;

CREATE TABLE "user" (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY, --pkey
    musicbrainz_row_id  INTEGER UNIQUE,
    user_email          TEXT UNIQUE,
    digest              BOOLEAN DEFAULT FALSE,
    digest_age          SMALLINT -- in days.
);

ALTER TABLE "user" ADD CONSTRAINT user_pkey PRIMARY KEY (id);

COMMIT;