BEGIN;

CREATE TYPE notification_project_type AS ENUM (
    'metabrainz',
    'musicbrainz',
    'listenbrainz',
    'bookbrainz',
    'critiquebrainz'
);

CREATE TABLE notifications (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY, -- primary key.
    user_id         INTEGER NOT NULL, -- foreign key to user's table musicbrainz_row_id.
    project         notification_project_type NOT NULL,
    read            BOOLEAN DEFAULT FALSE,
    created_ts      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expire_age      SMALLINT, -- in days.
    important       BOOLEAN DEFAULT FALSE,
    email_id        TEXT,
    subject         TEXT NOT NULL,
    body            TEXT NOT NULL,
    template_id     TEXT, --MB Mail template id.
    template_params JSONB --params for given MB Mail template.

);
ALTER TABLE notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE notifications
    ADD CONSTRAINT notifications_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES "user" (musicbrainz_row_id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

COMMIT;