BEGIN;

CREATE TABLE user_preference (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY, --pkey
    musicbrainz_row_id  INTEGER UNIQUE, --TODO: foreign key to user's table musicbrainz_row_id.
    notifications_enabled BOOLEAN DEFAULT TRUE,
    digest              BOOLEAN DEFAULT FALSE,
    digest_age          SMALLINT -- in days.
);

ALTER TABLE user_preference ADD CONSTRAINT user_preference_pkey PRIMARY KEY (id);

COMMIT;