BEGIN;

CREATE TABLE "user" (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY, --pkey
    musicbrainz_row_id  INTEGER UNIQUE,
    digest              BOOLEAN DEFAULT FALSE,
    digest_age          INTEGER
);

COMMIT;