BEGIN;

ALTER TABLE "user" ADD COLUMN is_blocked BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE moderation_log (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id                 INTEGER NOT NULL,
    moderator_id            INTEGER NOT NULL,
    action                  moderation_action_type NOT NULL,
    reason                  TEXT NOT NULL,
    timestamp               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
ALTER TABLE moderation_log ADD CONSTRAINT moderation_log_pkey PRIMARY KEY (id);
ALTER TABLE moderation_log ADD CONSTRAINT moderation_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id);
ALTER TABLE moderation_log ADD CONSTRAINT moderation_log_moderator_id_fkey FOREIGN KEY (moderator_id) REFERENCES "user" (id);
CREATE INDEX moderation_log_user_id_idx ON moderation_log (user_id);

ALTER TABLE "user" ADD COLUMN login_id UUID NOT NULL;
CREATE UNIQUE INDEX user_login_id_idx ON "user" (login_id);

COMMIT;
