CREATE TYPE moderation_action_type AS ENUM ('block', 'unblock');

BEGIN;

CREATE TABLE moderation_log (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id                 INTEGER NOT NULL,
    moderator_id            INTEGER NOT NULL,
    action                  moderation_action_type NOT NULL,
    reason                  TEXT NOT NULL,
    timestamp               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
ALTER TABLE moderation_log ADD CONSTRAINT moderation_log_pkey PRIMARY KEY (id);
ALTER TABLE moderation_log ADD CONSTRAINT moderation_log_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES "user" (id)
    ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE moderation_log ADD CONSTRAINT moderation_log_moderator_id_fkey
    FOREIGN KEY (moderator_id) REFERENCES "user" (id)
    ON UPDATE CASCADE ON DELETE SET NULL;
CREATE INDEX moderation_log_user_id_idx ON moderation_log (user_id);

COMMIT;
