BEGIN;

CREATE TABLE oauth.provisioned_user (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER NOT NULL,
        client_id INTEGER NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE oauth.provisioned_user ADD CONSTRAINT provisioned_user_pkey PRIMARY KEY (id);

ALTER TABLE oauth.provisioned_user
    ADD CONSTRAINT provisioned_user_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES "user" (id) ON DELETE CASCADE;

ALTER TABLE oauth.provisioned_user
    ADD CONSTRAINT provisioned_user_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES oauth.client (id) ON DELETE CASCADE;

-- an account is provisioned once, by the one client that created it
CREATE UNIQUE INDEX provisioned_user_user_id_uniq_idx ON oauth.provisioned_user (user_id);
CREATE INDEX provisioned_user_client_id_idx ON oauth.provisioned_user (client_id);

COMMIT;
