BEGIN;

ALTER TABLE oauth.scope ADD COLUMN restricted BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE oauth.l_client_scope (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        client_id INTEGER NOT NULL,
        scope_id INTEGER NOT NULL
);

ALTER TABLE oauth.l_client_scope ADD CONSTRAINT l_client_scope_pkey PRIMARY KEY (id);

ALTER TABLE oauth.l_client_scope
    ADD CONSTRAINT l_client_scope_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES oauth.client (id) ON DELETE CASCADE;

ALTER TABLE oauth.l_client_scope
    ADD CONSTRAINT l_client_scope_scope_id_fkey FOREIGN KEY (scope_id)
    REFERENCES oauth.scope (id) ON DELETE CASCADE;

CREATE UNIQUE INDEX l_client_scope_uniq_idx ON oauth.l_client_scope (client_id, scope_id);
CREATE INDEX l_client_scope_scope_id_idx ON oauth.l_client_scope (scope_id);

COMMIT;
