BEGIN;

CREATE TABLE "user" (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    login_id                UUID NOT NULL,
    name                    TEXT NOT NULL,
    password                TEXT NOT NULL,
    email                   TEXT,
    unconfirmed_email       TEXT,
    email_confirmed_at      TIMESTAMP WITH TIME ZONE,
    member_since            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_login_at           TIMESTAMP WITH TIME ZONE,
    last_updated            TIMESTAMP WITH TIME ZONE,
    deleted                 BOOLEAN NOT NULL DEFAULT FALSE,
    is_blocked              BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE "user" ADD CONSTRAINT user_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX user_login_id_idx ON "user" (login_id);
CREATE UNIQUE INDEX user_name_unq_idx ON "user" (name);

COMMIT;
