# -*- coding: utf-8 -*-
# Default values for configuration variables

PAYMENT_PRODUCTION = False

WEPAY_ACCOUNT_ID = ""
WEPAY_ACCESS_TOKEN = ""

PAYPAL_PRIMARY_EMAIL = ""
PAYPAL_BUSINESS = ""

STRIPE_KEYS = {
    "SECRET": "",
    "PUBLISHABLE": "",
}
STRIPE_TEST_KEYS = {
    "SECRET": "",
    "PUBLISHABLE": "",
}


MUSICBRAINZ_BASE_URL = "https://musicbrainz.org/"
MUSICBRAINZ_CLIENT_ID = ""
MUSICBRAINZ_CLIENT_SECRET = ""


ADMINS = []


RECAPTCHA_PUBLIC_KEY = ""
RECAPTCHA_PRIVATE_KEY = ""


NOTIFICATION_RECIPIENTS = []


PREFERRED_URL_SCHEME = "http"
