BEGIN;

CREATE schema oauth;

CREATE TABLE oauth.scope (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        description TEXT NOT NULL
);

INSERT INTO oauth.scope (name, description)
     VALUES ('profile', 'View your public account information')
          , ('email', 'View your email address')
          , ('musicbrainz:tag', 'View and modify your private tags')
          , ('musicbrainz:rating', 'View and modify your private ratings')
          , ('musicbrainz:collection', 'View and modify your private collections')
          , ('musicbrainz:submit_isrc', 'Submit new ISRCs to the database')
          , ('musicbrainz:submit_barcode', 'Submit new barcodes to the database')
          , ('openid', 'Sign you in and view your unique user id')
          , ('listenbrainz:submit-listens', 'Submit listens to ListenBrainz.')
          , ('critiquebrainz:review', 'Create and modify CritiqueBrainz reviews.')
          , ('critiquebrainz:vote', 'Submit and delete votes on CritiqueBrainz reviews.')
          , ('critiquebrainz:profile', 'Modify profile info and delete profile on CritiqueBrainz.');

CREATE TABLE oauth.client (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        client_id TEXT NOT NULL,
        client_secret TEXT,
        owner_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        website TEXT,
        redirect_uris TEXT[] NOT NULL,
        client_id_issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
        privileges INTEGER NOT NULL DEFAULT 0 CONSTRAINT client_privileges_non_negative CHECK (privileges >= 0)
);

CREATE TABLE oauth.code (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER NOT NULL,
        client_id INTEGER NOT NULL,
        code TEXT NOT NULL,
        redirect_uri TEXT NOT NULL,
        code_challenge TEXT,
        code_challenge_method TEXT,
        issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
        expires_in INTEGER,
        revoked BOOLEAN,
        nonce TEXT
);

CREATE TABLE oauth.access_token (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER, -- null for tokens issued by client_credentials grant
        client_id INTEGER NOT NULL,
        authorization_code_id INTEGER,
        access_token TEXT NOT NULL,
        issued_at TIMESTAMP WITH TIME ZONE,
        expires_in INTEGER,
        revoked BOOLEAN
);

CREATE TABLE oauth.refresh_token (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER NOT NULL,
        client_id INTEGER NOT NULL,
        authorization_code_id INTEGER,
        refresh_token TEXT NOT NULL,
        issued_at TIMESTAMP WITH TIME ZONE,
        expires_in INTEGER,
        revoked BOOLEAN
);

CREATE TABLE oauth.l_access_token_scope (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        access_token_id INTEGER NOT NULL,
        scope_id INTEGER NOT NULL
);

CREATE TABLE oauth.l_refresh_token_scope (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        refresh_token_id INTEGER NOT NULL,
        scope_id INTEGER NOT NULL
);

CREATE TABLE oauth.l_code_scope (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        code_id INTEGER NOT NULL,
        scope_id INTEGER NOT NULL
);

COMMIT;
