# -*- coding: utf-8 -*-
#
# MetaBrainz documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

from datetime import datetime

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
#
# These docs are hand-written narrative and HTTP-endpoint reference; they do
# not autodoc the application, so no extension here imports the Flask app.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinxcontrib.httpdomain',
    'sphinx.ext.autosectionlabel',
    'sphinx_rtd_theme',
]
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'MetaBrainz'
copyright = f'2014-{datetime.now().year}, MetaBrainz Foundation'
author = u'MetaBrainz Foundation'
html_baseurl = 'https://metabrainz.readthedocs.io/en/latest/'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1.0'
# The full version, including alpha/beta/rc tags.
release = '0.1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'collapse_navigation': False,
    'version_selector': False,
    'navigation_depth': 3,
}

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = "MetaBrainz docs"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "../frontend/img/logo.svg"

# The name of an image file (relative to this directory) to use as favicon of
# the docs.
html_favicon = "../frontend/img/favicon-32.png"

# Language to be used for generating the HTML full-text search index.
html_search_language = 'en'

# Output file base name for HTML help builder.
htmlhelp_basename = 'MetaBrainzdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  (master_doc, 'MetaBrainz.tex', u'MetaBrainz Documentation',
   u'MetaBrainz Foundation', 'manual'),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'metabrainz', u'MetaBrainz Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  (master_doc, 'MetaBrainz', u'MetaBrainz Documentation',
   author, 'MetaBrainz', 'Website for the MetaBrainz Foundation.',
   'Miscellaneous'),
]
