name: MetaBrainz Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create configuration file
      run: cp config.py.example config.py

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      continue-on-error: true

    - name: Run tests
      run: ./test.sh

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.11
      if: ${{ always() }}
      with:
        files: reports/tests.xml
